### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by apps4u** [AFNetworking/AFHTTPRequestOperationLogger#22] opened 2013-12-09 03:09 UTC
I had to remove strong from two properties that are blocks in
AFURLConnectionOperation.h
As its the only way my project will build on Xcode 5 runnig os x 10.9, and iOS 7 and only if AFHTTPRequestOperationLogger cocoapod is installed if that pod is not installed AFNetworking will build without me needing to edit the two properties. but once I re add the logger then I have to edit AFNetworking to not get errors during build

/**
 The dispatch queue for `completionBlock`. If `NULL` (default), the main queue is used.
 */
@property (nonatomic) dispatch_queue_t completionQueue;

/**
 The dispatch group for `completionBlock`. If `NULL` (default), a private dispatch group is used.
 */
@property (nonatomic) dispatch_group_t completionGroup;

**Comment by febeling** [comment] 2014-04-17 13:53
Same here.

**Comment by Broich** [comment] 2014-05-27 11:07
+1

**Comment by fishkingsin** [comment] 2014-06-21 03:19
I don't know is it a right way 
it can be built after I modified

"AFNetworking/NSURLConnection/AFURLConnectionOperation.h"
from 

```

/**
 The dispatch queue for `completionBlock`. If `NULL` (default), the main queue is used.
 */
@property (nonatomic, strong) dispatch_queue_t completionQueue;

/**
 The dispatch group for `completionBlock`. If `NULL` (default), a private dispatch group is used.
 */
@property (nonatomic, strong) dispatch_group_t completionGroup;

```

to

```

/**
 The dispatch queue for `completionBlock`. If `NULL` (default), the main queue is used.
 */
@property (nonatomic, assign) dispatch_queue_t completionQueue;

/**
 The dispatch group for `completionBlock`. If `NULL` (default), a private dispatch group is used.
 */
@property (nonatomic, assign) dispatch_group_t completionGroup;

```

**Comment by mattt** [comment] 2014-07-18 07:29
Duplicate of AFNetworking/AFNetworking#1614. See https://github.com/AFNetworking/AFNetworking/wiki/AFNetworking-FAQ#im-getting-compiler-errors-about-dispatch_queue_t-being-a-strong-property-whats-up-with-that

**Closed as completed by mattt** 2014-07-18 07:29 UTC
